version: '2.1'
services:
  upesi-api:
    container_name: upesi-api
    restart: on-failure
    build:
      context: .
      dockerfile: development/Dockerfile
    working_dir: /usr/src/app
    ports:
      - '5900:5900'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      database:
        condition: service_healthy
  redis:
    image: redis:5.0.10
    container_name: cache
    ports:
      - '6379:6379'
  database:
    container_name: database
    restart: on-failure
    build:
      context: .
      dockerfile: development/database/Dockerfile
    ports:
      - '8435:5433'
    environment:
      PGUSER: upesi
      PGPASSWORD: upesi
      PGDATABASE: upesi
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 15s
      timeout: 5s
      retries: 10
    volumes:
      - ${PWD}/.env:/.env
      - ./development/database/init-db.sh:/docker-entrypoint-initdb.d/2-init-db.sh
