export const resources = [
  'view dashboard',
  'create job',
  'update job',
  'delete job',
  'list jobs',
  'view job',
  'create task',
  'update task',
  'delete task',
  'list tasks',
  'view task',
  'create user',
  'update user',
  'delete user',
  'list user',
  'view user',
  'reset password',
  'block user',
  'force password change',
  'create client',
  'update client',
  'delete client',
  'list clients',
  'view client',
  'create status',
  'update status',
  'delete status',
  'list status',
  'view status',
  'list roles',
  'administer roles',
  'view merging queue',
  'perform spot check',
  'transcribe',
  'peer-review',
  'quality-control',
  'assign task',
  'assign job',
  'view delivery queue',
  'list rsync files',
  'manage groups',
  'list groups',
  'list taxonomy',
  'view taxonomy',
  'list tags',
  'view tag',
  'view task report',
];
